// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `bumper.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <bumper.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 4
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompBumper__Bumper__enable_name = "enable";

const ::std::string __RoboCompBumper__Bumper__disable_name = "disable";

const ::std::string __RoboCompBumper__Bumper__isEnabled_name = "isEnabled";

const ::std::string __RoboCompBumper__Bumper__reset_name = "reset";

const ::std::string __RoboCompBumper__Bumper__getSensorData_name = "getSensorData";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::RoboCompBumper::upCast(::IceProxy::RoboCompBumper::Bumper* p) { return p; }

void
::IceProxy::RoboCompBumper::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompBumper::Bumper>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompBumper::Bumper;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::RoboCompBumper::Bumper::enable(const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __RoboCompBumper__Bumper__enable_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompBumper::Bumper::begin_enable(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompBumper__Bumper__enable_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompBumper__Bumper__enable_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompBumper::Bumper::end_enable(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompBumper__Bumper__enable_name);
}

void
IceProxy::RoboCompBumper::Bumper::disable(const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __RoboCompBumper__Bumper__disable_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompBumper::Bumper::begin_disable(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompBumper__Bumper__disable_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompBumper__Bumper__disable_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompBumper::Bumper::end_disable(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompBumper__Bumper__disable_name);
}

bool
IceProxy::RoboCompBumper::Bumper::isEnabled(const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RoboCompBumper__Bumper__isEnabled_name);
    ::IceInternal::Outgoing __og(this, __RoboCompBumper__Bumper__isEnabled_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    bool __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompBumper::Bumper::begin_isEnabled(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompBumper__Bumper__isEnabled_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompBumper__Bumper__isEnabled_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompBumper__Bumper__isEnabled_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RoboCompBumper::Bumper::__begin_isEnabled(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (bool)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RoboCompBumper::BumperPrx __proxy = ::RoboCompBumper::BumperPrx::uncheckedCast(__result->getProxy());
            bool __ret;
            try
            {
                __ret = __proxy->end_isEnabled(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret);
            }
        }
    
    private:
        
        ::std::function<void (bool)> _response;
    };
    return begin_isEnabled(__ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

bool
IceProxy::RoboCompBumper::Bumper::end_isEnabled(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompBumper__Bumper__isEnabled_name);
    bool __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

void
IceProxy::RoboCompBumper::Bumper::reset(const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __RoboCompBumper__Bumper__reset_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompBumper::Bumper::begin_reset(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompBumper__Bumper__reset_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompBumper__Bumper__reset_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompBumper::Bumper::end_reset(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompBumper__Bumper__reset_name);
}

::RoboCompBumper::SensorStateMap
IceProxy::RoboCompBumper::Bumper::getSensorData(const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RoboCompBumper__Bumper__getSensorData_name);
    ::IceInternal::Outgoing __og(this, __RoboCompBumper__Bumper__getSensorData_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::RoboCompBumper::SensorStateMap __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompBumper::Bumper::begin_getSensorData(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompBumper__Bumper__getSensorData_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompBumper__Bumper__getSensorData_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompBumper__Bumper__getSensorData_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RoboCompBumper::Bumper::__begin_getSensorData(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::RoboCompBumper::SensorStateMap&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (const ::RoboCompBumper::SensorStateMap&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RoboCompBumper::BumperPrx __proxy = ::RoboCompBumper::BumperPrx::uncheckedCast(__result->getProxy());
            ::RoboCompBumper::SensorStateMap __ret;
            try
            {
                __ret = __proxy->end_getSensorData(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret);
            }
        }
    
    private:
        
        ::std::function<void (const ::RoboCompBumper::SensorStateMap&)> _response;
    };
    return begin_getSensorData(__ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

::RoboCompBumper::SensorStateMap
IceProxy::RoboCompBumper::Bumper::end_getSensorData(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompBumper__Bumper__getSensorData_name);
    ::RoboCompBumper::SensorStateMap __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

const ::std::string&
IceProxy::RoboCompBumper::Bumper::ice_staticId()
{
    return ::RoboCompBumper::Bumper::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::RoboCompBumper::Bumper::__newInstance() const
{
    return new Bumper;
}

::Ice::Object* RoboCompBumper::upCast(::RoboCompBumper::Bumper* p) { return p; }

namespace
{
const ::std::string __RoboCompBumper__Bumper_ids[2] =
{
    "::Ice::Object",
    "::RoboCompBumper::Bumper"
};

}

bool
RoboCompBumper::Bumper::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompBumper__Bumper_ids, __RoboCompBumper__Bumper_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompBumper::Bumper::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompBumper__Bumper_ids[0], &__RoboCompBumper__Bumper_ids[2]);
}

const ::std::string&
RoboCompBumper::Bumper::ice_id(const ::Ice::Current&) const
{
    return __RoboCompBumper__Bumper_ids[1];
}

const ::std::string&
RoboCompBumper::Bumper::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompBumper::Bumper";
    return typeId;
#else
    return __RoboCompBumper__Bumper_ids[1];
#endif
}

::Ice::DispatchStatus
RoboCompBumper::Bumper::___enable(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    enable(__current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompBumper::Bumper::___disable(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    disable(__current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompBumper::Bumper::___isEnabled(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    bool __ret = isEnabled(__current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompBumper::Bumper::___reset(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    reset(__current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompBumper::Bumper::___getSensorData(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::RoboCompBumper::SensorStateMap __ret = getSensorData(__current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompBumper__Bumper_all[] =
{
    "disable",
    "enable",
    "getSensorData",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "isEnabled",
    "reset"
};

}

::Ice::DispatchStatus
RoboCompBumper::Bumper::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompBumper__Bumper_all, __RoboCompBumper__Bumper_all + 9, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompBumper__Bumper_all)
    {
        case 0:
        {
            return ___disable(in, current);
        }
        case 1:
        {
            return ___enable(in, current);
        }
        case 2:
        {
            return ___getSensorData(in, current);
        }
        case 3:
        {
            return ___ice_id(in, current);
        }
        case 4:
        {
            return ___ice_ids(in, current);
        }
        case 5:
        {
            return ___ice_isA(in, current);
        }
        case 6:
        {
            return ___ice_ping(in, current);
        }
        case 7:
        {
            return ___isEnabled(in, current);
        }
        case 8:
        {
            return ___reset(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompBumper::Bumper::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompBumper::Bumper::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompBumper::__patch(BumperPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompBumper::BumperPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompBumper::Bumper::ice_staticId(), v);
    }
}
