// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `DifferentialRobot.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <DifferentialRobot.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 4
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompDifferentialRobot__DifferentialRobot__getBaseState_name = "getBaseState";

const ::std::string __RoboCompDifferentialRobot__DifferentialRobot__getBasePose_name = "getBasePose";

const ::std::string __RoboCompDifferentialRobot__DifferentialRobot__setSpeedBase_name = "setSpeedBase";

const ::std::string __RoboCompDifferentialRobot__DifferentialRobot__stopBase_name = "stopBase";

const ::std::string __RoboCompDifferentialRobot__DifferentialRobot__resetOdometer_name = "resetOdometer";

const ::std::string __RoboCompDifferentialRobot__DifferentialRobot__setOdometer_name = "setOdometer";

const ::std::string __RoboCompDifferentialRobot__DifferentialRobot__setOdometerPose_name = "setOdometerPose";

const ::std::string __RoboCompDifferentialRobot__DifferentialRobot__correctOdometer_name = "correctOdometer";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::RoboCompDifferentialRobot::upCast(::IceProxy::RoboCompDifferentialRobot::DifferentialRobot* p) { return p; }

void
::IceProxy::RoboCompDifferentialRobot::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompDifferentialRobot::DifferentialRobot>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompDifferentialRobot::DifferentialRobot;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::getBaseState(::RoboCompGenericBase::TBaseState& __p_state, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RoboCompDifferentialRobot__DifferentialRobot__getBaseState_name);
    ::IceInternal::Outgoing __og(this, __RoboCompDifferentialRobot__DifferentialRobot__getBaseState_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__p_state);
    __og.endReadParams();
}

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::begin_getBaseState(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompDifferentialRobot__DifferentialRobot__getBaseState_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompDifferentialRobot__DifferentialRobot__getBaseState_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompDifferentialRobot__DifferentialRobot__getBaseState_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::__begin_getBaseState(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::RoboCompGenericBase::TBaseState&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (const ::RoboCompGenericBase::TBaseState&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RoboCompDifferentialRobot::DifferentialRobotPrx __proxy = ::RoboCompDifferentialRobot::DifferentialRobotPrx::uncheckedCast(__result->getProxy());
            ::RoboCompGenericBase::TBaseState __p_state;
            try
            {
                __proxy->end_getBaseState(__p_state, __result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__p_state);
            }
        }
    
    private:
        
        ::std::function<void (const ::RoboCompGenericBase::TBaseState&)> _response;
    };
    return begin_getBaseState(__ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::end_getBaseState(::RoboCompGenericBase::TBaseState& __p_state, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompDifferentialRobot__DifferentialRobot__getBaseState_name);
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__p_state);
    __result->__endReadParams();
}

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::getBasePose(::Ice::Int& __p_x, ::Ice::Int& __p_z, ::Ice::Float& __p_alpha, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RoboCompDifferentialRobot__DifferentialRobot__getBasePose_name);
    ::IceInternal::Outgoing __og(this, __RoboCompDifferentialRobot__DifferentialRobot__getBasePose_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__p_x);
    __is->read(__p_z);
    __is->read(__p_alpha);
    __og.endReadParams();
}

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::begin_getBasePose(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompDifferentialRobot__DifferentialRobot__getBasePose_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompDifferentialRobot__DifferentialRobot__getBasePose_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompDifferentialRobot__DifferentialRobot__getBasePose_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::__begin_getBasePose(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Int, ::Ice::Int, ::Ice::Float)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (::Ice::Int, ::Ice::Int, ::Ice::Float)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RoboCompDifferentialRobot::DifferentialRobotPrx __proxy = ::RoboCompDifferentialRobot::DifferentialRobotPrx::uncheckedCast(__result->getProxy());
            ::Ice::Int __p_x;
            ::Ice::Int __p_z;
            ::Ice::Float __p_alpha;
            try
            {
                __proxy->end_getBasePose(__p_x, __p_z, __p_alpha, __result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__p_x, __p_z, __p_alpha);
            }
        }
    
    private:
        
        ::std::function<void (::Ice::Int, ::Ice::Int, ::Ice::Float)> _response;
    };
    return begin_getBasePose(__ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::end_getBasePose(::Ice::Int& __p_x, ::Ice::Int& __p_z, ::Ice::Float& __p_alpha, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompDifferentialRobot__DifferentialRobot__getBasePose_name);
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__p_x);
    __is->read(__p_z);
    __is->read(__p_alpha);
    __result->__endReadParams();
}

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::setSpeedBase(::Ice::Float __p_adv, ::Ice::Float __p_rot, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RoboCompDifferentialRobot__DifferentialRobot__setSpeedBase_name);
    ::IceInternal::Outgoing __og(this, __RoboCompDifferentialRobot__DifferentialRobot__setSpeedBase_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_adv);
        __os->write(__p_rot);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::begin_setSpeedBase(::Ice::Float __p_adv, ::Ice::Float __p_rot, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompDifferentialRobot__DifferentialRobot__setSpeedBase_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompDifferentialRobot__DifferentialRobot__setSpeedBase_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompDifferentialRobot__DifferentialRobot__setSpeedBase_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_adv);
        __os->write(__p_rot);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::__begin_setSpeedBase(::Ice::Float __p_adv, ::Ice::Float __p_rot, const ::Ice::Context* __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void ()>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RoboCompDifferentialRobot::DifferentialRobotPrx __proxy = ::RoboCompDifferentialRobot::DifferentialRobotPrx::uncheckedCast(__result->getProxy());
            try
            {
                __proxy->end_setSpeedBase(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response();
            }
        }
    
    private:
        
        ::std::function<void ()> _response;
    };
    return begin_setSpeedBase(__p_adv, __p_rot, __ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::end_setSpeedBase(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompDifferentialRobot__DifferentialRobot__setSpeedBase_name);
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    __result->__readEmptyParams();
}

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::stopBase(const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RoboCompDifferentialRobot__DifferentialRobot__stopBase_name);
    ::IceInternal::Outgoing __og(this, __RoboCompDifferentialRobot__DifferentialRobot__stopBase_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::begin_stopBase(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompDifferentialRobot__DifferentialRobot__stopBase_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompDifferentialRobot__DifferentialRobot__stopBase_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompDifferentialRobot__DifferentialRobot__stopBase_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::__begin_stopBase(const ::Ice::Context* __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void ()>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RoboCompDifferentialRobot::DifferentialRobotPrx __proxy = ::RoboCompDifferentialRobot::DifferentialRobotPrx::uncheckedCast(__result->getProxy());
            try
            {
                __proxy->end_stopBase(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response();
            }
        }
    
    private:
        
        ::std::function<void ()> _response;
    };
    return begin_stopBase(__ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::end_stopBase(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompDifferentialRobot__DifferentialRobot__stopBase_name);
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    __result->__readEmptyParams();
}

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::resetOdometer(const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RoboCompDifferentialRobot__DifferentialRobot__resetOdometer_name);
    ::IceInternal::Outgoing __og(this, __RoboCompDifferentialRobot__DifferentialRobot__resetOdometer_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::begin_resetOdometer(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompDifferentialRobot__DifferentialRobot__resetOdometer_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompDifferentialRobot__DifferentialRobot__resetOdometer_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompDifferentialRobot__DifferentialRobot__resetOdometer_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::__begin_resetOdometer(const ::Ice::Context* __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void ()>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RoboCompDifferentialRobot::DifferentialRobotPrx __proxy = ::RoboCompDifferentialRobot::DifferentialRobotPrx::uncheckedCast(__result->getProxy());
            try
            {
                __proxy->end_resetOdometer(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response();
            }
        }
    
    private:
        
        ::std::function<void ()> _response;
    };
    return begin_resetOdometer(__ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::end_resetOdometer(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompDifferentialRobot__DifferentialRobot__resetOdometer_name);
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    __result->__readEmptyParams();
}

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::setOdometer(const ::RoboCompGenericBase::TBaseState& __p_state, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RoboCompDifferentialRobot__DifferentialRobot__setOdometer_name);
    ::IceInternal::Outgoing __og(this, __RoboCompDifferentialRobot__DifferentialRobot__setOdometer_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_state);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::begin_setOdometer(const ::RoboCompGenericBase::TBaseState& __p_state, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompDifferentialRobot__DifferentialRobot__setOdometer_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompDifferentialRobot__DifferentialRobot__setOdometer_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompDifferentialRobot__DifferentialRobot__setOdometer_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_state);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::__begin_setOdometer(const ::RoboCompGenericBase::TBaseState& __p_state, const ::Ice::Context* __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void ()>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RoboCompDifferentialRobot::DifferentialRobotPrx __proxy = ::RoboCompDifferentialRobot::DifferentialRobotPrx::uncheckedCast(__result->getProxy());
            try
            {
                __proxy->end_setOdometer(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response();
            }
        }
    
    private:
        
        ::std::function<void ()> _response;
    };
    return begin_setOdometer(__p_state, __ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::end_setOdometer(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompDifferentialRobot__DifferentialRobot__setOdometer_name);
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    __result->__readEmptyParams();
}

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::setOdometerPose(::Ice::Int __p_x, ::Ice::Int __p_z, ::Ice::Float __p_alpha, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RoboCompDifferentialRobot__DifferentialRobot__setOdometerPose_name);
    ::IceInternal::Outgoing __og(this, __RoboCompDifferentialRobot__DifferentialRobot__setOdometerPose_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_x);
        __os->write(__p_z);
        __os->write(__p_alpha);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::begin_setOdometerPose(::Ice::Int __p_x, ::Ice::Int __p_z, ::Ice::Float __p_alpha, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompDifferentialRobot__DifferentialRobot__setOdometerPose_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompDifferentialRobot__DifferentialRobot__setOdometerPose_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompDifferentialRobot__DifferentialRobot__setOdometerPose_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_x);
        __os->write(__p_z);
        __os->write(__p_alpha);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::__begin_setOdometerPose(::Ice::Int __p_x, ::Ice::Int __p_z, ::Ice::Float __p_alpha, const ::Ice::Context* __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void ()>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RoboCompDifferentialRobot::DifferentialRobotPrx __proxy = ::RoboCompDifferentialRobot::DifferentialRobotPrx::uncheckedCast(__result->getProxy());
            try
            {
                __proxy->end_setOdometerPose(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response();
            }
        }
    
    private:
        
        ::std::function<void ()> _response;
    };
    return begin_setOdometerPose(__p_x, __p_z, __p_alpha, __ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::end_setOdometerPose(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompDifferentialRobot__DifferentialRobot__setOdometerPose_name);
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    __result->__readEmptyParams();
}

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::correctOdometer(::Ice::Int __p_x, ::Ice::Int __p_z, ::Ice::Float __p_alpha, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RoboCompDifferentialRobot__DifferentialRobot__correctOdometer_name);
    ::IceInternal::Outgoing __og(this, __RoboCompDifferentialRobot__DifferentialRobot__correctOdometer_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_x);
        __os->write(__p_z);
        __os->write(__p_alpha);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::begin_correctOdometer(::Ice::Int __p_x, ::Ice::Int __p_z, ::Ice::Float __p_alpha, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompDifferentialRobot__DifferentialRobot__correctOdometer_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompDifferentialRobot__DifferentialRobot__correctOdometer_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompDifferentialRobot__DifferentialRobot__correctOdometer_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_x);
        __os->write(__p_z);
        __os->write(__p_alpha);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::__begin_correctOdometer(::Ice::Int __p_x, ::Ice::Int __p_z, ::Ice::Float __p_alpha, const ::Ice::Context* __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void ()>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RoboCompDifferentialRobot::DifferentialRobotPrx __proxy = ::RoboCompDifferentialRobot::DifferentialRobotPrx::uncheckedCast(__result->getProxy());
            try
            {
                __proxy->end_correctOdometer(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response();
            }
        }
    
    private:
        
        ::std::function<void ()> _response;
    };
    return begin_correctOdometer(__p_x, __p_z, __p_alpha, __ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::end_correctOdometer(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompDifferentialRobot__DifferentialRobot__correctOdometer_name);
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    __result->__readEmptyParams();
}

const ::std::string&
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::ice_staticId()
{
    return ::RoboCompDifferentialRobot::DifferentialRobot::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::__newInstance() const
{
    return new DifferentialRobot;
}

::Ice::Object* RoboCompDifferentialRobot::upCast(::RoboCompDifferentialRobot::DifferentialRobot* p) { return p; }

namespace
{
const ::std::string __RoboCompDifferentialRobot__DifferentialRobot_ids[2] =
{
    "::Ice::Object",
    "::RoboCompDifferentialRobot::DifferentialRobot"
};

}

bool
RoboCompDifferentialRobot::DifferentialRobot::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompDifferentialRobot__DifferentialRobot_ids, __RoboCompDifferentialRobot__DifferentialRobot_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompDifferentialRobot::DifferentialRobot::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompDifferentialRobot__DifferentialRobot_ids[0], &__RoboCompDifferentialRobot__DifferentialRobot_ids[2]);
}

const ::std::string&
RoboCompDifferentialRobot::DifferentialRobot::ice_id(const ::Ice::Current&) const
{
    return __RoboCompDifferentialRobot__DifferentialRobot_ids[1];
}

const ::std::string&
RoboCompDifferentialRobot::DifferentialRobot::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompDifferentialRobot::DifferentialRobot";
    return typeId;
#else
    return __RoboCompDifferentialRobot__DifferentialRobot_ids[1];
#endif
}

::Ice::DispatchStatus
RoboCompDifferentialRobot::DifferentialRobot::___getBaseState(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::RoboCompGenericBase::TBaseState __p_state;
    try
    {
        getBaseState(__p_state, __current);
        ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_state);
        __inS.__endWriteParams(true);
        return ::Ice::DispatchOK;
    }
    catch(const ::RoboCompGenericBase::HardwareFailedException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

::Ice::DispatchStatus
RoboCompDifferentialRobot::DifferentialRobot::___getBasePose(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::Ice::Int __p_x;
    ::Ice::Int __p_z;
    ::Ice::Float __p_alpha;
    try
    {
        getBasePose(__p_x, __p_z, __p_alpha, __current);
        ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_x);
        __os->write(__p_z);
        __os->write(__p_alpha);
        __inS.__endWriteParams(true);
        return ::Ice::DispatchOK;
    }
    catch(const ::RoboCompGenericBase::HardwareFailedException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

::Ice::DispatchStatus
RoboCompDifferentialRobot::DifferentialRobot::___setSpeedBase(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Ice::Float __p_adv;
    ::Ice::Float __p_rot;
    __is->read(__p_adv);
    __is->read(__p_rot);
    __inS.endReadParams();
    try
    {
        setSpeedBase(__p_adv, __p_rot, __current);
        __inS.__writeEmptyParams();
        return ::Ice::DispatchOK;
    }
    catch(const ::RoboCompGenericBase::HardwareFailedException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

::Ice::DispatchStatus
RoboCompDifferentialRobot::DifferentialRobot::___stopBase(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    try
    {
        stopBase(__current);
        __inS.__writeEmptyParams();
        return ::Ice::DispatchOK;
    }
    catch(const ::RoboCompGenericBase::HardwareFailedException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

::Ice::DispatchStatus
RoboCompDifferentialRobot::DifferentialRobot::___resetOdometer(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    try
    {
        resetOdometer(__current);
        __inS.__writeEmptyParams();
        return ::Ice::DispatchOK;
    }
    catch(const ::RoboCompGenericBase::HardwareFailedException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

::Ice::DispatchStatus
RoboCompDifferentialRobot::DifferentialRobot::___setOdometer(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompGenericBase::TBaseState __p_state;
    __is->read(__p_state);
    __inS.endReadParams();
    try
    {
        setOdometer(__p_state, __current);
        __inS.__writeEmptyParams();
        return ::Ice::DispatchOK;
    }
    catch(const ::RoboCompGenericBase::HardwareFailedException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

::Ice::DispatchStatus
RoboCompDifferentialRobot::DifferentialRobot::___setOdometerPose(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Ice::Int __p_x;
    ::Ice::Int __p_z;
    ::Ice::Float __p_alpha;
    __is->read(__p_x);
    __is->read(__p_z);
    __is->read(__p_alpha);
    __inS.endReadParams();
    try
    {
        setOdometerPose(__p_x, __p_z, __p_alpha, __current);
        __inS.__writeEmptyParams();
        return ::Ice::DispatchOK;
    }
    catch(const ::RoboCompGenericBase::HardwareFailedException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

::Ice::DispatchStatus
RoboCompDifferentialRobot::DifferentialRobot::___correctOdometer(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Ice::Int __p_x;
    ::Ice::Int __p_z;
    ::Ice::Float __p_alpha;
    __is->read(__p_x);
    __is->read(__p_z);
    __is->read(__p_alpha);
    __inS.endReadParams();
    try
    {
        correctOdometer(__p_x, __p_z, __p_alpha, __current);
        __inS.__writeEmptyParams();
        return ::Ice::DispatchOK;
    }
    catch(const ::RoboCompGenericBase::HardwareFailedException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

namespace
{
const ::std::string __RoboCompDifferentialRobot__DifferentialRobot_all[] =
{
    "correctOdometer",
    "getBasePose",
    "getBaseState",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "resetOdometer",
    "setOdometer",
    "setOdometerPose",
    "setSpeedBase",
    "stopBase"
};

}

::Ice::DispatchStatus
RoboCompDifferentialRobot::DifferentialRobot::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompDifferentialRobot__DifferentialRobot_all, __RoboCompDifferentialRobot__DifferentialRobot_all + 12, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompDifferentialRobot__DifferentialRobot_all)
    {
        case 0:
        {
            return ___correctOdometer(in, current);
        }
        case 1:
        {
            return ___getBasePose(in, current);
        }
        case 2:
        {
            return ___getBaseState(in, current);
        }
        case 3:
        {
            return ___ice_id(in, current);
        }
        case 4:
        {
            return ___ice_ids(in, current);
        }
        case 5:
        {
            return ___ice_isA(in, current);
        }
        case 6:
        {
            return ___ice_ping(in, current);
        }
        case 7:
        {
            return ___resetOdometer(in, current);
        }
        case 8:
        {
            return ___setOdometer(in, current);
        }
        case 9:
        {
            return ___setOdometerPose(in, current);
        }
        case 10:
        {
            return ___setSpeedBase(in, current);
        }
        case 11:
        {
            return ___stopBase(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompDifferentialRobot::DifferentialRobot::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompDifferentialRobot::DifferentialRobot::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompDifferentialRobot::__patch(DifferentialRobotPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompDifferentialRobot::DifferentialRobotPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompDifferentialRobot::DifferentialRobot::ice_staticId(), v);
    }
}
