// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `GenericBase.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <GenericBase.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 4
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompGenericBase__GenericBase__getBaseState_name = "getBaseState";

const ::std::string __RoboCompGenericBase__GenericBase__getBasePose_name = "getBasePose";

}

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit< ::RoboCompGenericBase::HardwareFailedException> __RoboCompGenericBase__HardwareFailedException_init("::RoboCompGenericBase::HardwareFailedException");

}

RoboCompGenericBase::HardwareFailedException::HardwareFailedException(const ::std::string& __ice_what) :
    ::Ice::UserException(),
    what(__ice_what)
{
}

RoboCompGenericBase::HardwareFailedException::~HardwareFailedException() throw()
{
}

::std::string
RoboCompGenericBase::HardwareFailedException::ice_name() const
{
    return "RoboCompGenericBase::HardwareFailedException";
}

RoboCompGenericBase::HardwareFailedException*
RoboCompGenericBase::HardwareFailedException::ice_clone() const
{
    return new HardwareFailedException(*this);
}

void
RoboCompGenericBase::HardwareFailedException::ice_throw() const
{
    throw *this;
}

void
RoboCompGenericBase::HardwareFailedException::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice("::RoboCompGenericBase::HardwareFailedException", -1, true);
    __os->write(what);
    __os->endWriteSlice();
}

void
RoboCompGenericBase::HardwareFailedException::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->read(what);
    __is->endReadSlice();
}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::RoboCompGenericBase::upCast(::IceProxy::RoboCompGenericBase::GenericBase* p) { return p; }

void
::IceProxy::RoboCompGenericBase::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompGenericBase::GenericBase>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompGenericBase::GenericBase;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::RoboCompGenericBase::GenericBase::getBaseState(::RoboCompGenericBase::TBaseState& __p_state, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RoboCompGenericBase__GenericBase__getBaseState_name);
    ::IceInternal::Outgoing __og(this, __RoboCompGenericBase__GenericBase__getBaseState_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__p_state);
    __og.endReadParams();
}

::Ice::AsyncResultPtr
IceProxy::RoboCompGenericBase::GenericBase::begin_getBaseState(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompGenericBase__GenericBase__getBaseState_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompGenericBase__GenericBase__getBaseState_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompGenericBase__GenericBase__getBaseState_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RoboCompGenericBase::GenericBase::__begin_getBaseState(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::RoboCompGenericBase::TBaseState&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (const ::RoboCompGenericBase::TBaseState&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RoboCompGenericBase::GenericBasePrx __proxy = ::RoboCompGenericBase::GenericBasePrx::uncheckedCast(__result->getProxy());
            ::RoboCompGenericBase::TBaseState __p_state;
            try
            {
                __proxy->end_getBaseState(__p_state, __result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__p_state);
            }
        }
    
    private:
        
        ::std::function<void (const ::RoboCompGenericBase::TBaseState&)> _response;
    };
    return begin_getBaseState(__ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

void
IceProxy::RoboCompGenericBase::GenericBase::end_getBaseState(::RoboCompGenericBase::TBaseState& __p_state, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompGenericBase__GenericBase__getBaseState_name);
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__p_state);
    __result->__endReadParams();
}

void
IceProxy::RoboCompGenericBase::GenericBase::getBasePose(::Ice::Int& __p_x, ::Ice::Int& __p_z, ::Ice::Float& __p_alpha, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RoboCompGenericBase__GenericBase__getBasePose_name);
    ::IceInternal::Outgoing __og(this, __RoboCompGenericBase__GenericBase__getBasePose_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__p_x);
    __is->read(__p_z);
    __is->read(__p_alpha);
    __og.endReadParams();
}

::Ice::AsyncResultPtr
IceProxy::RoboCompGenericBase::GenericBase::begin_getBasePose(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompGenericBase__GenericBase__getBasePose_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompGenericBase__GenericBase__getBasePose_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompGenericBase__GenericBase__getBasePose_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RoboCompGenericBase::GenericBase::__begin_getBasePose(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Int, ::Ice::Int, ::Ice::Float)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (::Ice::Int, ::Ice::Int, ::Ice::Float)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RoboCompGenericBase::GenericBasePrx __proxy = ::RoboCompGenericBase::GenericBasePrx::uncheckedCast(__result->getProxy());
            ::Ice::Int __p_x;
            ::Ice::Int __p_z;
            ::Ice::Float __p_alpha;
            try
            {
                __proxy->end_getBasePose(__p_x, __p_z, __p_alpha, __result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__p_x, __p_z, __p_alpha);
            }
        }
    
    private:
        
        ::std::function<void (::Ice::Int, ::Ice::Int, ::Ice::Float)> _response;
    };
    return begin_getBasePose(__ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

void
IceProxy::RoboCompGenericBase::GenericBase::end_getBasePose(::Ice::Int& __p_x, ::Ice::Int& __p_z, ::Ice::Float& __p_alpha, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompGenericBase__GenericBase__getBasePose_name);
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__p_x);
    __is->read(__p_z);
    __is->read(__p_alpha);
    __result->__endReadParams();
}

const ::std::string&
IceProxy::RoboCompGenericBase::GenericBase::ice_staticId()
{
    return ::RoboCompGenericBase::GenericBase::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::RoboCompGenericBase::GenericBase::__newInstance() const
{
    return new GenericBase;
}

::Ice::Object* RoboCompGenericBase::upCast(::RoboCompGenericBase::GenericBase* p) { return p; }

namespace
{
const ::std::string __RoboCompGenericBase__GenericBase_ids[2] =
{
    "::Ice::Object",
    "::RoboCompGenericBase::GenericBase"
};

}

bool
RoboCompGenericBase::GenericBase::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompGenericBase__GenericBase_ids, __RoboCompGenericBase__GenericBase_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompGenericBase::GenericBase::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompGenericBase__GenericBase_ids[0], &__RoboCompGenericBase__GenericBase_ids[2]);
}

const ::std::string&
RoboCompGenericBase::GenericBase::ice_id(const ::Ice::Current&) const
{
    return __RoboCompGenericBase__GenericBase_ids[1];
}

const ::std::string&
RoboCompGenericBase::GenericBase::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompGenericBase::GenericBase";
    return typeId;
#else
    return __RoboCompGenericBase__GenericBase_ids[1];
#endif
}

::Ice::DispatchStatus
RoboCompGenericBase::GenericBase::___getBaseState(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::RoboCompGenericBase::TBaseState __p_state;
    try
    {
        getBaseState(__p_state, __current);
        ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_state);
        __inS.__endWriteParams(true);
        return ::Ice::DispatchOK;
    }
    catch(const ::RoboCompGenericBase::HardwareFailedException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

::Ice::DispatchStatus
RoboCompGenericBase::GenericBase::___getBasePose(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::Ice::Int __p_x;
    ::Ice::Int __p_z;
    ::Ice::Float __p_alpha;
    try
    {
        getBasePose(__p_x, __p_z, __p_alpha, __current);
        ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_x);
        __os->write(__p_z);
        __os->write(__p_alpha);
        __inS.__endWriteParams(true);
        return ::Ice::DispatchOK;
    }
    catch(const ::RoboCompGenericBase::HardwareFailedException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

namespace
{
const ::std::string __RoboCompGenericBase__GenericBase_all[] =
{
    "getBasePose",
    "getBaseState",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
RoboCompGenericBase::GenericBase::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompGenericBase__GenericBase_all, __RoboCompGenericBase__GenericBase_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompGenericBase__GenericBase_all)
    {
        case 0:
        {
            return ___getBasePose(in, current);
        }
        case 1:
        {
            return ___getBaseState(in, current);
        }
        case 2:
        {
            return ___ice_id(in, current);
        }
        case 3:
        {
            return ___ice_ids(in, current);
        }
        case 4:
        {
            return ___ice_isA(in, current);
        }
        case 5:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompGenericBase::GenericBase::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompGenericBase::GenericBase::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompGenericBase::__patch(GenericBasePtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompGenericBase::GenericBasePtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompGenericBase::GenericBase::ice_staticId(), v);
    }
}
