// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Laser.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Laser.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 4
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompLaser__Laser__getLaserData_name = "getLaserData";

const ::std::string __RoboCompLaser__Laser__getLaserAndBStateData_name = "getLaserAndBStateData";

const ::std::string __RoboCompLaser__Laser__getLaserConfData_name = "getLaserConfData";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::RoboCompLaser::upCast(::IceProxy::RoboCompLaser::Laser* p) { return p; }

void
::IceProxy::RoboCompLaser::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompLaser::Laser>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompLaser::Laser;
        v->__copyFrom(proxy);
    }
}

::RoboCompLaser::TLaserData
IceProxy::RoboCompLaser::Laser::getLaserData(const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RoboCompLaser__Laser__getLaserData_name);
    ::IceInternal::Outgoing __og(this, __RoboCompLaser__Laser__getLaserData_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::RoboCompLaser::TLaserData __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompLaser::Laser::begin_getLaserData(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompLaser__Laser__getLaserData_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompLaser__Laser__getLaserData_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompLaser__Laser__getLaserData_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RoboCompLaser::Laser::__begin_getLaserData(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::RoboCompLaser::TLaserData&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (const ::RoboCompLaser::TLaserData&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RoboCompLaser::LaserPrx __proxy = ::RoboCompLaser::LaserPrx::uncheckedCast(__result->getProxy());
            ::RoboCompLaser::TLaserData __ret;
            try
            {
                __ret = __proxy->end_getLaserData(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret);
            }
        }
    
    private:
        
        ::std::function<void (const ::RoboCompLaser::TLaserData&)> _response;
    };
    return begin_getLaserData(__ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

::RoboCompLaser::TLaserData
IceProxy::RoboCompLaser::Laser::end_getLaserData(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompLaser__Laser__getLaserData_name);
    ::RoboCompLaser::TLaserData __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

::RoboCompLaser::TLaserData
IceProxy::RoboCompLaser::Laser::getLaserAndBStateData(::RoboCompGenericBase::TBaseState& __p_bState, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RoboCompLaser__Laser__getLaserAndBStateData_name);
    ::IceInternal::Outgoing __og(this, __RoboCompLaser__Laser__getLaserAndBStateData_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::RoboCompLaser::TLaserData __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__p_bState);
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompLaser::Laser::begin_getLaserAndBStateData(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompLaser__Laser__getLaserAndBStateData_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompLaser__Laser__getLaserAndBStateData_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompLaser__Laser__getLaserAndBStateData_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RoboCompLaser::Laser::__begin_getLaserAndBStateData(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::RoboCompLaser::TLaserData&, const ::RoboCompGenericBase::TBaseState&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (const ::RoboCompLaser::TLaserData&, const ::RoboCompGenericBase::TBaseState&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RoboCompLaser::LaserPrx __proxy = ::RoboCompLaser::LaserPrx::uncheckedCast(__result->getProxy());
            ::RoboCompGenericBase::TBaseState __p_bState;
            ::RoboCompLaser::TLaserData __ret;
            try
            {
                __ret = __proxy->end_getLaserAndBStateData(__p_bState, __result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret, __p_bState);
            }
        }
    
    private:
        
        ::std::function<void (const ::RoboCompLaser::TLaserData&, const ::RoboCompGenericBase::TBaseState&)> _response;
    };
    return begin_getLaserAndBStateData(__ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

::RoboCompLaser::TLaserData
IceProxy::RoboCompLaser::Laser::end_getLaserAndBStateData(::RoboCompGenericBase::TBaseState& __p_bState, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompLaser__Laser__getLaserAndBStateData_name);
    ::RoboCompLaser::TLaserData __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__p_bState);
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

::RoboCompLaser::LaserConfData
IceProxy::RoboCompLaser::Laser::getLaserConfData(const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RoboCompLaser__Laser__getLaserConfData_name);
    ::IceInternal::Outgoing __og(this, __RoboCompLaser__Laser__getLaserConfData_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::RoboCompLaser::LaserConfData __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompLaser::Laser::begin_getLaserConfData(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompLaser__Laser__getLaserConfData_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompLaser__Laser__getLaserConfData_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompLaser__Laser__getLaserConfData_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RoboCompLaser::Laser::__begin_getLaserConfData(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::RoboCompLaser::LaserConfData&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (const ::RoboCompLaser::LaserConfData&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RoboCompLaser::LaserPrx __proxy = ::RoboCompLaser::LaserPrx::uncheckedCast(__result->getProxy());
            ::RoboCompLaser::LaserConfData __ret;
            try
            {
                __ret = __proxy->end_getLaserConfData(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret);
            }
        }
    
    private:
        
        ::std::function<void (const ::RoboCompLaser::LaserConfData&)> _response;
    };
    return begin_getLaserConfData(__ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

::RoboCompLaser::LaserConfData
IceProxy::RoboCompLaser::Laser::end_getLaserConfData(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompLaser__Laser__getLaserConfData_name);
    ::RoboCompLaser::LaserConfData __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

const ::std::string&
IceProxy::RoboCompLaser::Laser::ice_staticId()
{
    return ::RoboCompLaser::Laser::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::RoboCompLaser::Laser::__newInstance() const
{
    return new Laser;
}

::Ice::Object* RoboCompLaser::upCast(::RoboCompLaser::Laser* p) { return p; }

namespace
{
const ::std::string __RoboCompLaser__Laser_ids[2] =
{
    "::Ice::Object",
    "::RoboCompLaser::Laser"
};

}

bool
RoboCompLaser::Laser::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompLaser__Laser_ids, __RoboCompLaser__Laser_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompLaser::Laser::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompLaser__Laser_ids[0], &__RoboCompLaser__Laser_ids[2]);
}

const ::std::string&
RoboCompLaser::Laser::ice_id(const ::Ice::Current&) const
{
    return __RoboCompLaser__Laser_ids[1];
}

const ::std::string&
RoboCompLaser::Laser::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompLaser::Laser";
    return typeId;
#else
    return __RoboCompLaser__Laser_ids[1];
#endif
}

::Ice::DispatchStatus
RoboCompLaser::Laser::___getLaserData(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::RoboCompLaser::TLaserData __ret = getLaserData(__current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompLaser::Laser::___getLaserAndBStateData(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::RoboCompGenericBase::TBaseState __p_bState;
    ::RoboCompLaser::TLaserData __ret = getLaserAndBStateData(__p_bState, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__p_bState);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompLaser::Laser::___getLaserConfData(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::RoboCompLaser::LaserConfData __ret = getLaserConfData(__current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompLaser__Laser_all[] =
{
    "getLaserAndBStateData",
    "getLaserConfData",
    "getLaserData",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
RoboCompLaser::Laser::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompLaser__Laser_all, __RoboCompLaser__Laser_all + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompLaser__Laser_all)
    {
        case 0:
        {
            return ___getLaserAndBStateData(in, current);
        }
        case 1:
        {
            return ___getLaserConfData(in, current);
        }
        case 2:
        {
            return ___getLaserData(in, current);
        }
        case 3:
        {
            return ___ice_id(in, current);
        }
        case 4:
        {
            return ___ice_ids(in, current);
        }
        case 5:
        {
            return ___ice_isA(in, current);
        }
        case 6:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompLaser::Laser::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompLaser::Laser::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompLaser::__patch(LaserPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompLaser::LaserPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompLaser::Laser::ice_staticId(), v);
    }
}
