// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Motors.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Motors.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 4
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompMotors__Motors__getMotorSpeed_name = "getMotorSpeed";

const ::std::string __RoboCompMotors__Motors__setMotorSpeed_name = "setMotorSpeed";

}
::IceProxy::Ice::Object* ::IceProxy::RoboCompMotors::upCast(::IceProxy::RoboCompMotors::Motors* p) { return p; }

void
::IceProxy::RoboCompMotors::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompMotors::Motors>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompMotors::Motors;
        v->__copyFrom(proxy);
    }
}

::Ice::Float
IceProxy::RoboCompMotors::Motors::getMotorSpeed(const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__RoboCompMotors__Motors__getMotorSpeed_name);
    ::IceInternal::Outgoing __og(this, __RoboCompMotors__Motors__getMotorSpeed_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::Ice::Float __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompMotors::Motors::begin_getMotorSpeed(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompMotors__Motors__getMotorSpeed_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompMotors__Motors__getMotorSpeed_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompMotors__Motors__getMotorSpeed_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::RoboCompMotors::Motors::__begin_getMotorSpeed(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Float)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (::Ice::Float)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::RoboCompMotors::MotorsPrx __proxy = ::RoboCompMotors::MotorsPrx::uncheckedCast(__result->getProxy());
            ::Ice::Float __ret;
            try
            {
                __ret = __proxy->end_getMotorSpeed(__result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret);
            }
        }
    
    private:
        
        ::std::function<void (::Ice::Float)> _response;
    };
    return begin_getMotorSpeed(__ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

::Ice::Float
IceProxy::RoboCompMotors::Motors::end_getMotorSpeed(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompMotors__Motors__getMotorSpeed_name);
    ::Ice::Float __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

void
IceProxy::RoboCompMotors::Motors::setMotorSpeed(::Ice::Float __p_w, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __RoboCompMotors__Motors__setMotorSpeed_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_w);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompMotors::Motors::begin_setMotorSpeed(::Ice::Float __p_w, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompMotors__Motors__setMotorSpeed_name, __del, __cookie);
    try
    {
        __result->prepare(__RoboCompMotors__Motors__setMotorSpeed_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_w);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompMotors::Motors::end_setMotorSpeed(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompMotors__Motors__setMotorSpeed_name);
}

const ::std::string&
IceProxy::RoboCompMotors::Motors::ice_staticId()
{
    return ::RoboCompMotors::Motors::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::RoboCompMotors::Motors::__newInstance() const
{
    return new Motors;
}

::Ice::Object* RoboCompMotors::upCast(::RoboCompMotors::Motors* p) { return p; }

namespace
{
const ::std::string __RoboCompMotors__Motors_ids[2] =
{
    "::Ice::Object",
    "::RoboCompMotors::Motors"
};

}

bool
RoboCompMotors::Motors::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompMotors__Motors_ids, __RoboCompMotors__Motors_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompMotors::Motors::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompMotors__Motors_ids[0], &__RoboCompMotors__Motors_ids[2]);
}

const ::std::string&
RoboCompMotors::Motors::ice_id(const ::Ice::Current&) const
{
    return __RoboCompMotors__Motors_ids[1];
}

const ::std::string&
RoboCompMotors::Motors::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompMotors::Motors";
    return typeId;
#else
    return __RoboCompMotors__Motors_ids[1];
#endif
}

::Ice::DispatchStatus
RoboCompMotors::Motors::___getMotorSpeed(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::Ice::Float __ret = getMotorSpeed(__current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompMotors::Motors::___setMotorSpeed(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Ice::Float __p_w;
    __is->read(__p_w);
    __inS.endReadParams();
    setMotorSpeed(__p_w, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompMotors__Motors_all[] =
{
    "getMotorSpeed",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "setMotorSpeed"
};

}

::Ice::DispatchStatus
RoboCompMotors::Motors::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompMotors__Motors_all, __RoboCompMotors__Motors_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompMotors__Motors_all)
    {
        case 0:
        {
            return ___getMotorSpeed(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
        case 5:
        {
            return ___setMotorSpeed(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompMotors::Motors::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompMotors::Motors::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompMotors::__patch(MotorsPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompMotors::MotorsPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompMotors::Motors::ice_staticId(), v);
    }
}
