// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Exceptions.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ___home_ironman_gazebo_robocomp_slice____slice_cpp_Exceptions_h__
#define ___home_ironman_gazebo_robocomp_slice____slice_cpp_Exceptions_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 4
#       error Ice patch level mismatch!
#   endif
#endif

namespace RoboCompExceptions
{

class RoboCompException : public ::Ice::UserException
{
public:

    RoboCompException() {}
    explicit RoboCompException(const ::std::string&);
    virtual ~RoboCompException() throw();

    virtual ::std::string ice_name() const;
    virtual RoboCompException* ice_clone() const;
    virtual void ice_throw() const;

    ::std::string what;

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::UserException::__writeImpl;
    using ::Ice::UserException::__readImpl;
};

static RoboCompException __RoboCompException_init;

class ConfigurationNotExistException : public ::RoboCompExceptions::RoboCompException
{
public:

    ConfigurationNotExistException() {}
    explicit ConfigurationNotExistException(const ::std::string&);
    virtual ~ConfigurationNotExistException() throw();

    virtual ::std::string ice_name() const;
    virtual ConfigurationNotExistException* ice_clone() const;
    virtual void ice_throw() const;

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::RoboCompExceptions::RoboCompException::__writeImpl;
    using ::RoboCompExceptions::RoboCompException::__readImpl;
};

class DataNotExistException : public ::RoboCompExceptions::RoboCompException
{
public:

    DataNotExistException() {}
    explicit DataNotExistException(const ::std::string&);
    virtual ~DataNotExistException() throw();

    virtual ::std::string ice_name() const;
    virtual DataNotExistException* ice_clone() const;
    virtual void ice_throw() const;

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::RoboCompExceptions::RoboCompException::__writeImpl;
    using ::RoboCompExceptions::RoboCompException::__readImpl;
};

class HardwareFailedException : public ::RoboCompExceptions::RoboCompException
{
public:

    HardwareFailedException() {}
    explicit HardwareFailedException(const ::std::string&);
    virtual ~HardwareFailedException() throw();

    virtual ::std::string ice_name() const;
    virtual HardwareFailedException* ice_clone() const;
    virtual void ice_throw() const;

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::RoboCompExceptions::RoboCompException::__writeImpl;
    using ::RoboCompExceptions::RoboCompException::__readImpl;
};

class NoTopicException : public ::RoboCompExceptions::RoboCompException
{
public:

    NoTopicException() {}
    explicit NoTopicException(const ::std::string&);
    virtual ~NoTopicException() throw();

    virtual ::std::string ice_name() const;
    virtual NoTopicException* ice_clone() const;
    virtual void ice_throw() const;

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::RoboCompExceptions::RoboCompException::__writeImpl;
    using ::RoboCompExceptions::RoboCompException::__readImpl;
};

class SubscriptionFailedException : public ::RoboCompExceptions::RoboCompException
{
public:

    SubscriptionFailedException() {}
    explicit SubscriptionFailedException(const ::std::string&);
    virtual ~SubscriptionFailedException() throw();

    virtual ::std::string ice_name() const;
    virtual SubscriptionFailedException* ice_clone() const;
    virtual void ice_throw() const;

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::RoboCompExceptions::RoboCompException::__writeImpl;
    using ::RoboCompExceptions::RoboCompException::__readImpl;
};

class SubscriptionPushFailedException : public ::RoboCompExceptions::RoboCompException
{
public:

    SubscriptionPushFailedException() {}
    explicit SubscriptionPushFailedException(const ::std::string&);
    virtual ~SubscriptionPushFailedException() throw();

    virtual ::std::string ice_name() const;
    virtual SubscriptionPushFailedException* ice_clone() const;
    virtual void ice_throw() const;

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::RoboCompExceptions::RoboCompException::__writeImpl;
    using ::RoboCompExceptions::RoboCompException::__readImpl;
};

}

namespace Ice
{
template<>
struct StreamableTraits< ::RoboCompExceptions::RoboCompException>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

template<>
struct StreamableTraits< ::RoboCompExceptions::ConfigurationNotExistException>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

template<>
struct StreamableTraits< ::RoboCompExceptions::DataNotExistException>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

template<>
struct StreamableTraits< ::RoboCompExceptions::HardwareFailedException>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

template<>
struct StreamableTraits< ::RoboCompExceptions::NoTopicException>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

template<>
struct StreamableTraits< ::RoboCompExceptions::SubscriptionFailedException>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

template<>
struct StreamableTraits< ::RoboCompExceptions::SubscriptionPushFailedException>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

}

#include <IceUtil/PopDisableWarnings.h>
#endif
